# Trauma note - the YML here has been massively shat up by goob.

# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTLeaderGearEVA
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTLeader
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives". Is never used anywhere else.
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon
    # - MagazineMagnum - No need

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    neck: ExecutiveIDCard # Goob - was Whistle
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives". Is never used anywhere else.
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon
    #- MagazineMagnum # Goob

- type: startingGear
  parent: ERTLeaderGearEVA
  id: ERTLeaderGearArmed
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponRifleLecterXL8
  storage:
    back:
    - HoloprojectorField
    - PhoneInstrument
    - PinpointerNuclear
    - MagazineRifle
    - MagazineRifle
    - MagazineRifleIncendiary
    - MagazineRifleUranium
    - MedkitCombatFilled # End of first line
    - GrenadeShrapnel
    - EmpGrenade

- type: chameleonOutfit
  id: ERTLeaderChameleonOutfit
  job: ERTLeader
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTLeader
    neck: ClothingNeckBronzeheart

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: CurseImmune # Goobstation - Wraith
    - type: CanEnchant #GoobStation
  - !type:AddImplantSpecial
     implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTChaplainGearEVA
  id: ERTChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHatFez
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: DrinkWaterBottleFull
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    - DrinkWaterMelonJuiceJug
    - Lantern
    - Lantern
    - ChaplainUndeterminedBible # Goobstation
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Nullrod # Goobstation
    - Lighter
    - ExecutiveIDCard # Goobstation - Executive Access!

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
  storage:
    back:
    - BoxCandle
    - BoxBodyBag
    - DrinkWaterMelonJuiceJug
    - Lantern
    - Lantern
    - ChaplainUndeterminedBible # Goobstation
    - CrowbarRed
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - Lighter
    - Nullrod # Goobstation
    - ExecutiveIDCard # Goobstation - Executive Access!

- type: chameleonOutfit
  id: ERTChaplainChameleonOutfit
  job: ERTChaplain
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTChaplain
    mask: ClothingMaskGasERT
    outerClothing: ClothingOuterHardsuitERTChaplain
    shoes: ClothingShoesBootsMagAdv

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTEngineerGearEVA
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTEngineer
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMeson
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: GasAnalyzer
  storage:
    back:
    - trayScanner
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CableMVStack
    - CableHVStack
    - CableApcStack
    - SheetPlasteel
    - SheetSteel
    - SheetGlass

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudDiagnostic
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
  storage:
    back:
    - RCD
    - GasAnalyzer
    - trayScanner
    - HolofanProjector
    - PartRodMetal
    - SheetPlasteel # End of first line
    - MiningDrillDiamond
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - MetalFoamGrenade
    - AirGrenade
    belt:
    - JawsOfLife
    - PowerDrill
    - WelderIndustrialAdvanced
    - Multitool
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: startingGear
  parent: ERTEngineerGearEVA
  id: ERTEngineerGearArmed
  equipment:
    suitstorage: WeaponShotgunEnforcer
  storage:
    back:
    - RCD
    - GasAnalyzer
    - HolofanProjector
    - MiningDrillDiamond
    - BoxLethalshot
    - BoxShotgunSlug # End of first line
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - CableDetStack
    - BoxDetonator

- type: chameleonOutfit
  id: ERTEngineerChameleonOutfit
  job: ERTEngineer
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTEngineer
    neck: ClothingNeckEngineermedal

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTSecurityGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm]

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTSecurity
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - CrowbarRed
    - ERTSecurityUndeterminedWeapon
   # - MagazinePistol

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goob - was Whistle
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssaultFilled # Goobstation
    pocket1: WeaponPulsePistol # Death to Crew aligned Ballistics
    pocket2: FlashlightSeclite
  storage:
    back:
    # - WeaponDisabler - Redundant. It spawns in secbelts now.
    - MedkitCombatFilled # Goobstation - No reason not to.
    - BoxZiptie
    - Flash
    - GrenadeFlashBang
    - TearGasGrenade
    - GrenadeStinger
    - MedkitCombatFilled # End of first line
    - TelescopicShield
    - HoloprojectorSecurity
    - PowerCellHigh

- type: startingGear
  id: ERTSecurityGearArmedRifle
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    shoes: ClothingShoesBootsMagERT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT
    pocket2: CombatKnife
    suitstorage: WeaponRifleLecter
  inhand:
    - WeaponLaserCannon
    - PortableRecharger
  storage:
    belt:
    - CrowbarRed
    - Zipties
    - MedkitCombatFilled
    - MagazineRifle
    - MagazineRifle
    - MagazineRifleIncendiary
    - MagazineRifleUranium
    - Zipties

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGearArmedGrenade
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponLauncherHydraLethal
  storage:
    back:
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - GrenadeBlast
    - MagazinePistol
    - MedkitCombatFilled # End of first line
    - GrenadeEMP
    - GrenadeEMP
    - GrenadeEMP
    - GrenadeFlash
    - GrenadeFlash
    - GrenadeFlash
    - MagazinePistol

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGearArmedVanguard
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponSubMachineGunWt550
  storage:
    back:
    - ExGrenade
    - SmokeGrenade
    - EmpGrenade
    - HoloprojectorSecurity
    - TelescopicShield
    - TelescopicShield
    - TelescopicShield
    - MedkitCombatFilled # End of first line
    - MagazinePistolSubMachineGunTopMounted
    - MagazinePistolSubMachineGunTopMounted
    - MagazinePistolSubMachineGunTopMounted
    - MagazinePistolSubMachineGunTopMounted

- type: startingGear
  parent: ERTSecurityGearEVA
  id: ERTSecurityGearArmedShotgun
  equipment:
    pocket2: WeaponDisabler
    suitstorage: WeaponShotgunEnforcer
  storage:
    back:
    - SmokeGrenade
    - BoxLethalshot
    - BoxShotgunSlug
    - BoxShotgunIncendiary
    - MedkitCombatFilled # End of first line
    - SmokeGrenade
    - ExGrenade
    - CableDetStack
    - BoxDetonator

- type: chameleonOutfit
  id: ERTSecurityChameleonOutfit
  job: ERTSecurity
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTSecurity
    neck: ClothingNeckSecuritymedal

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  parent: ERTMedicalGearEVA
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    head: ClothingHeadHelmetERTMedic
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Goobstation
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbingFilledMedical # Fancier
    pocket1: Flare
    pocket2: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - CentCommHypo
    - MedkitAdvancedFilled
    - CrowbarRed
    - ChemistryBottleOmnizine
    - JugOxandrolone
    - JugSalicylicAcid
    - ParamedHypo
    - CartridgeAtropine
    - CartridgeAtropine
    - MedicalBeamGunBattery

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    eyes: ClothingEyesGlassesMedSec # Goobstation
    gloves: ClothingHandsGlovesNitrile
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityWebbingFilledMedical # Fancier
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - CentCommHypo
    - MedkitAdvancedFilled
    - CrowbarRed
    - JugOxandrolone
    - JugSalicylicAcid
    - ParamedHypo
    - CartridgeAtropine
    - CartridgeAtropine
    - MedicalBeamGunBattery

- type: startingGear
  parent: ERTMedicalGearEVA
  id: ERTMedicalGearArmed
  equipment:
    suitstorage: WeaponRifleLecter
    pocket2: WeaponDisabler
  storage:
    back:
    - Hypospray
    - JugPunctTranex
    - JugPyraDerma
    - JugDexPlusSaline
    - JugTrico # End of first line
    - BeakerSmallArith
    - DefibrillatorCompact
    - MedkitCombatFilled
    - ClothingEyesGlassesChemical
    - ChemistryBottleOmnizine

- type: chameleonOutfit
  id: ERTMedicalChameleonOutfit
  job: ERTMedical
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTMedical
    neck: ClothingNeckStethoscope

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm]

- type: startingGear
  parent: ERTJanitorGearEVA
  id: ERTJanitorGear
  equipment:
    shoes: ClothingShoesGaloshes
    head: ClothingHeadHelmetERTJanitor
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterArmourDurathread # Durathread armor is cooler.
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - LightReplacer
    - BoxLightMixed
    - BoxLightMixed
    - Soap
    - CrowbarRed
    - AdvMopItem

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagEmergencyResponseTeam # Goobstation
    mask: ClothingMaskGasERT
    neck: ExecutiveIDCard # Goobstation - Executive Access!
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERT # Trauma - fit belt shit
    pocket1: WeaponPulsePistol # Literally described as "Favored sidearm of NT ERT operatives".
  storage:
    back:
    - TrashBag
    - SoapNT
    - Plunger
    - Screwdriver
    - AdvMopItem # End of first line
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    - GrenadeCleanade
    belt:
    - MegaSprayBottleSpaceCleaner
    - Holoprojector
    - LightReplacer
    - WireBrush
    - CrowbarRed
    - WeaponPistolMk58
    - MagazinePistol
    - EmergencyMedipen

- type: chameleonOutfit
  id: ERTJanitorChameleonOutfit
  job: ERTJanitor
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetHardsuitERTJanitor
    neck: ClothingNeckScarfStripedPurple
    eyes: ClothingEyesGlassesSunglasses
