- type: job
  id: CentralCommandOfficial
  name: job-name-centcommoff
  description: job-description-centcommoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcommGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom # Goobstation
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 21
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  # Goobstation
  - NanotrasenRepresentative
  - BlueshieldOfficer
  special: # Goobstation
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, FreedomImplant, BluespaceLifelineImplant, RadioImplantCentcomm, NutrimentPumpImplant, StypticStimulatorImplant, DeathRattleImplantCentcomm ]

- type: startingGear # Goobstation - Start - SolsticeOfTheWinter
  id: CentcommGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    shoes: ClothingShoesBootsJackFilled # Change this if you want, I don't really care.
    head: ClothingHeadHatCentcomcap # Lets be real, the other hat looks like steaming ASS.
    eyes: ClothingEyesGlassesCentComm # Goobstation
    gloves: ClothingHandsGlovesHeavyGoldenTrim # Goobstation
    back: ClothingBackpackSatchelLeather # Goobstation - Officials need bags too!
    outerClothing: ClothingOuterArmorCentcommCarapace # Officials shouldn't use shitty armor, Nanotrasen is richer than that.
    neck: ExecutiveIDCard # Executive Access!
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltHolsterFilledCentComm # was N1984
    pocket1: BoxFolderCentComClipboardThreePapers
    # pocket2: PenCentcom - Already has one in the PDA. This is redundant.
  storage:
    back:
    - HandheldFaxOfficial # NTRs fax is huge, do you expect me to use some POOR person fax?
    - BoxFolderCentComClipboard # Solely for holding and looking menacing.
    - DeterrentCaseFilled
# Goobstation - End

- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
