- type: entity
  abstract: true
  parent: [GunSafeBaseSecure, BaseSecurityContraband, AlertLevelLock]
  id: BaseTraumaGunSafe
  name: gun safe
  suffix: Alert Level Lock
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeLaserCarbine
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: Gunsafes
  - type: StationAlertLevelLock
    lockedAlertLevels:
    - green
    - blue
    - yellow

- type: entityTable
  id: FillLockerWardenTrauma
  table: !type:AllSelector
    children:
    - id: ClothingHandsGlovesKravMaga
    - id: BoxLethalInjection
    - id: ClothingHeadsetAltWarden
    - id: Multitool
    - id: Wrench
    - id: ContrabandDetectorFlatpack
    - id: SecurityMegaphone

- type: entityTable
  id: FillLockerSecurityTrauma
  table: !type:AllSelector
    children:
    - id: ClothingHeadsetAltSecurityRegular
    - id: PanicButton
    - id: PepperSpray

- type: entity
  parent: BaseTraumaGunSafe
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeLaserT1

- type: entity
  parent: BaseTraumaGunSafe
  id: GunSafeShotguns
  name: shotgun safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunsT1
  - type: StationAlertLevelLock
    lockedAlertLevels:
    - green
    - yellow

- type: entity
  parent: BaseTraumaGunSafe
  id: GunSafeLaserSpec
  name: specialist laser safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeLaserT2
  - type: StationAlertLevelLock
    lockedAlertLevels:
    - green
    - yellow

- type: entity
  parent: BaseTraumaGunSafe
  id: GunSafeMelee
  name: melee weapon safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeMeleeT1
  - type: StationAlertLevelLock
    lockedAlertLevels:
    - green
    - yellow

- type: entity
  parent: BaseTraumaGunSafe
  id: GunSafeJudo
  name: judo safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeJudoT1

- type: entity
  parent: BaseTraumaGunSafe
  id: GunSafeRiotLauncher
  name: riot launcher safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRiot

- type: entityTable
  id: FillGunSafeRiot
  table: !type:AllSelector
    children:
    - id: WeaponLauncherNonLethal
    - id: BoxGrenadesBaton
    - id: BoxGrenadesFlash
    - id: BoxGrenadesTeargas

- type: entityTable
  id: FillGunSafeLaserT1
  table: !type:AllSelector
    children:
    - id: WeaponLaserCarbine
      amount: 6

- type: entityTable
  id: FillGunSafeShotgunsT1
  table: !type:AllSelector
    children:
    - id: WeaponShotgunKammererEmpty
      amount: 3
    - id: BoxBeanbag
      amount: 3

- type: entityTable
  id: FillGunSafeLaserT2
  table: !type:AllSelector
    children:
    - id: WeaponTemperatureGun
    - id: WeaponEnergyIonRifle

- type: entityTable
  id: FillGunSafeMeleeT1
  table: !type:AllSelector
    children:
    - id: Truncheon
      amount: 6

- type: entityTable
  id: FillGunSafeJudoT1
  table: !type:AllSelector
    children:
    - id: ClothingBeltCorporateJudo
      amount: 2
